// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlacklistContent) DeepCopyInto(out *BlacklistContent) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlacklistContent.
func (in *BlacklistContent) DeepCopy() *BlacklistContent {
	if in == nil {
		return nil
	}
	out := new(BlacklistContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Executor) DeepCopyInto(out *Executor) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Executor.
func (in *Executor) DeepCopy() *Executor {
	if in == nil {
		return nil
	}
	out := new(Executor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOps) DeepCopyInto(out *GitOps) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOps.
func (in *GitOps) DeepCopy() *GitOps {
	if in == nil {
		return nil
	}
	out := new(GitOps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitOps) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsList) DeepCopyInto(out *GitOpsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitOps, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsList.
func (in *GitOpsList) DeepCopy() *GitOpsList {
	if in == nil {
		return nil
	}
	out := new(GitOpsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitOpsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsSpec) DeepCopyInto(out *GitOpsSpec) {
	*out = *in
	if in.Templating != nil {
		in, out := &in.Templating, &out.Templating
		*out = new(Templating)
		(*in).DeepCopyInto(*out)
	}
	if in.Reporting != nil {
		in, out := &in.Reporting, &out.Reporting
		*out = new(Reporting)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsSpec.
func (in *GitOpsSpec) DeepCopy() *GitOpsSpec {
	if in == nil {
		return nil
	}
	out := new(GitOpsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsStatus) DeepCopyInto(out *GitOpsStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsStatus.
func (in *GitOpsStatus) DeepCopy() *GitOpsStatus {
	if in == nil {
		return nil
	}
	out := new(GitOpsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reporting) DeepCopyInto(out *Reporting) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reporting.
func (in *Reporting) DeepCopy() *Reporting {
	if in == nil {
		return nil
	}
	out := new(Reporting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateDataSource) DeepCopyInto(out *TemplateDataSource) {
	*out = *in
	if in.TemplateDataFile != nil {
		in, out := &in.TemplateDataFile, &out.TemplateDataFile
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateDataSource.
func (in *TemplateDataSource) DeepCopy() *TemplateDataSource {
	if in == nil {
		return nil
	}
	out := new(TemplateDataSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Templating) DeepCopyInto(out *Templating) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(TemplateDataSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Executor != nil {
		in, out := &in.Executor, &out.Executor
		*out = new(Executor)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Templating.
func (in *Templating) DeepCopy() *Templating {
	if in == nil {
		return nil
	}
	out := new(Templating)
	in.DeepCopyInto(out)
	return out
}
