// Code generated by protoc-gen-go. DO NOT EDIT.
// source: report.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	report.proto

It has these top-level messages:
	UpdateResult
	Tags
	Empty
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateResult struct {
	Githash string  `protobuf:"bytes,1,opt,name=githash" json:"githash,omitempty"`
	Tags    []*Tags `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
}

func (m *UpdateResult) Reset()                    { *m = UpdateResult{} }
func (m *UpdateResult) String() string            { return proto1.CompactTextString(m) }
func (*UpdateResult) ProtoMessage()               {}
func (*UpdateResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpdateResult) GetGithash() string {
	if m != nil {
		return m.Githash
	}
	return ""
}

func (m *UpdateResult) GetTags() []*Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Tags struct {
	Key   string `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
}

func (m *Tags) Reset()                    { *m = Tags{} }
func (m *Tags) String() string            { return proto1.CompactTextString(m) }
func (*Tags) ProtoMessage()               {}
func (*Tags) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Tags) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Tags) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto1.RegisterType((*UpdateResult)(nil), "proto.UpdateResult")
	proto1.RegisterType((*Tags)(nil), "proto.Tags")
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Report service

type ReportClient interface {
	GitUpdate(ctx context.Context, in *UpdateResult, opts ...grpc.CallOption) (*Empty, error)
}

type reportClient struct {
	cc *grpc.ClientConn
}

func NewReportClient(cc *grpc.ClientConn) ReportClient {
	return &reportClient{cc}
}

func (c *reportClient) GitUpdate(ctx context.Context, in *UpdateResult, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.Report/GitUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Report service

type ReportServer interface {
	GitUpdate(context.Context, *UpdateResult) (*Empty, error)
}

func RegisterReportServer(s *grpc.Server, srv ReportServer) {
	s.RegisterService(&_Report_serviceDesc, srv)
}

func _Report_GitUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).GitUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Report/GitUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).GitUpdate(ctx, req.(*UpdateResult))
	}
	return interceptor(ctx, in, info, handler)
}

var _Report_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Report",
	HandlerType: (*ReportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GitUpdate",
			Handler:    _Report_GitUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report.proto",
}

func init() { proto1.RegisterFile("report.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0x2d, 0xc8,
	0x2f, 0x2a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x9e, 0x5c, 0x3c,
	0xa1, 0x05, 0x29, 0x89, 0x25, 0xa9, 0x41, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x42, 0x12, 0x5c, 0xec,
	0xe9, 0x99, 0x25, 0x19, 0x89, 0xc5, 0x19, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae,
	0x90, 0x3c, 0x17, 0x4b, 0x49, 0x62, 0x7a, 0xb1, 0x04, 0x93, 0x02, 0xb3, 0x06, 0xb7, 0x11, 0x37,
	0xc4, 0x18, 0xbd, 0x90, 0xc4, 0xf4, 0xe2, 0x20, 0xb0, 0x84, 0x92, 0x1e, 0x17, 0x0b, 0x88, 0x27,
	0x24, 0xc0, 0xc5, 0xec, 0x9d, 0x5a, 0x09, 0xd5, 0x0e, 0x62, 0x0a, 0x89, 0x70, 0xb1, 0x86, 0x25,
	0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x81, 0xc5, 0x20, 0x1c, 0x25, 0x76, 0x2e, 0x56, 0xd7, 0xdc, 0x82,
	0x92, 0x4a, 0x23, 0x0b, 0x2e, 0xb6, 0x20, 0xb0, 0xd3, 0x84, 0xf4, 0xb8, 0x38, 0xdd, 0x33, 0x4b,
	0x20, 0x0e, 0x12, 0x12, 0x86, 0x5a, 0x81, 0xec, 0x3e, 0x29, 0x1e, 0xa8, 0x20, 0x58, 0x67, 0x12,
	0x1b, 0x98, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x40, 0x64, 0x60, 0x3d, 0xdb, 0x00, 0x00,
	0x00,
}
